export const projects = [
  {
    title: 'React Travel App',
    description: "Example Travel Application, written in ReactJS.",
      image: '/images/example-travel-app.png',
      tags: ['React', 'CSS'],
    source: 'https://react-example-travel-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-travel-app',
    id: 0,
  },
  {
    title: 'React Gym App',
    description: "Gym application, written in ReactJS. The application allows users to search for different exercises that hit specific body parts.",
      image: '/images/gym-app.png',
      tags: ['React', 'Material UI'],
    source: 'https://react-gym-workout-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-gym-app',
    id: 1,
  },
  {
    title: 'React Restaurant App',
    description: "Restaurant application, written in ReactJS.",
      image: '/images/dining-app.png',
      tags: ['React', 'React Icons', 'CSS'],
    source: 'https://app.netlify.com/sites/react-fine-dining-app/overview',
    visit: 'https://github.com/automation-andy101/react-fine-dining-app',
    id: 2,
  },
  {
    title: 'React GPT-3 App',
    description: "GPT-3 application, written in ReactJS.",
      image: '/images/gpt3-app.png',
      tags: ['React', 'React Icons', 'CSS'],
    source: 'https://react-gpt3-website-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-gpt3-app',
    id: 3,
  },
  {
    title: 'React Example Banking App',
    description: "Banking application, written in ReactJS.",
      image: '/images/banking-app.png',
      tags: ['React', 'Vite', 'Tailwind'],
    source: 'https://react-example-bank-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-banking-app',
    id: 4,
  },
  {
    title: 'React Rick & Morty Wiki App',
    description: "Rick & Morty wiki application, written in ReactJS, with Bootstrap styling.",
      image: '/images/rick-morty.png',
      tags: ['React', 'Bootstrap'],
    source: 'https://react-rick-and-morty-wiki-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-rick-and-morty-wiki',
    id: 5,
  },
  {
    title: 'React Budget Planner App',
    description: "Budget Planner application, written in ReactJS, with Bootstrap styling.",
      image: '/images/budget-planner.png',
      tags: ['React', 'Bootstrap'],
    source: 'https://react-budgetplanner-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-budget-planner-app',
    id: 6,
  },
  {
    title: 'React Mortgage Calculator App',
    description: "Mortgage Calculator application, written in ReactJS, with Material UI styling.",
      image: '/images/mortgage-planner.png',
      tags: ['React', 'Material UI'],
    source: 'https://react-mortgage-planner-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-mortgage-calculator',
    id: 7,
  },
  {
    title: 'React Ecommerce Shop App',
    description: "Ecommerce Shop application, written in ReactJS.",
      image: '/images/ecommerse-shop.png',
      tags: ['React', 'Styled Components', 'Firebase'],
    source: 'https://react-crown-clothes-shop.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-clothes-shop-home',
    id: 8,
  },
];

export const TimeLineData = [
  { year: '2015-2019', text: 'Ultra Elctronics Airport Systems - Software Tester', },
  { year: '2019-2022', text: 'ADB Safegate Airport Systems - Software Tester', },
  { year: '2022-2023', text: 'Zaizi - Senior Software Tester', }
];