export const projects = [
  {
    title: 'React Travel App',
    description: "Example Travel Application, written in ReactJS.",
      image: '/images/example-travel-app.png',
      tags: ['React'],
    source: 'https://react-example-travel-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-travel-app',
    id: 0,
  },
  {
    title: 'React Gym App',
    description: "Gym application, written in ReactJS. The application allows users to search for different exercises that hit specific body parts.",
      image: '/images/gym-app.png',
      tags: ['React'],
    source: 'https://react-gym-workout-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-gym-app',
    id: 1,
  },
  {
    title: 'React Restaurant App',
    description: "Restaurant application, written in ReactJS.",
      image: '/images/dining-app.png',
      tags: ['React'],
    source: 'https://app.netlify.com/sites/react-fine-dining-app/overview',
    visit: 'https://github.com/automation-andy101/react-fine-dining-app',
    id: 2,
  },
  {
    title: 'React GPT-3 App',
    description: "GPT-3 application, written in ReactJS.",
      image: '/images/gpt3-app.png',
      tags: ['React'],
    source: 'https://react-gpt3-website-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-gpt3-app',
    id: 3,
  },
  {
    title: 'React Example Banking App',
    description: "Banking application, written in ReactJS.",
      image: '/images/banking-app.png',
      tags: ['React', 'Vite', 'Tailwind'],
    source: 'https://react-example-bank-app.netlify.app/',
    visit: 'https://github.com/automation-andy101/react-banking-app',
    id: 4,
  },
  // {
  //   title: 'React Ecommerce Shop App',
  //   description: "Ecommerce Shop application, written in ReactJS.",
  //     image: '/images/ecommerse-shop.png',
  //     tags: ['React', 'Styled Components', 'Firebase'],
  //   source: 'https://react-crown-clothes-shop.netlify.app/',
  //   visit: 'https://react-crown-clothes-shop.netlify.app/',
  //   id: 5,
  // },
  // {
  //   title: 'MERN Memories',
  //   description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
  //     image: '/images/1.png',
  //     tags: ['Mongo', 'Express', 'React', 'Node'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 6,
  // },
  // {
  //   title: 'E-Commerce',
  //   description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
  //   image: '/images/2.png',
  //   tags: ['React', 'JavaScript'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 7,
  // },
  // {
  //   title: 'WebRTC App',
  //   description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
  //     image: '/images/3.jpg',
  //     tags: ['React', 'WebRTC'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 8,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 9,
  // },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];